### ISSUE TITLE
Version `0.4.4` should be `0.5.0`

### ISSUE THREAD

**Issue by Swandog** [serverlesstechnology/postgres-es#6]
My reasoning is that the "Pool" types changed in `sqlx` 0.6.0, such that you can't use the types in `0.5.13`.

So if your `Cargo.toml` looks like this:
```
cqrs-es = "0.4.3"
postgres-es = "0.4.3"
sqlx = { version = "0.5.13", features = [ "postgres" , "runtime-tokio-rustls", "json"] }
```

Cargo will use `posrgres-es` version `0.4.4`, but still use `sqlx` version `0.5.13`, thus causing compile errors.

You can verify this by checking out the [cqrs-demo](https://github.com/serverlesstechnology/cqrs-demo), removing the `Cargo.lock`, and running `cargo build`.

(I'm still a bit new to Cargo versioning, so I apologize if I got anything mixed up)

**Comment by serverlesstechnology** [comment]
This is probably a valid argument. My apologies, I'll pay a bit closer attention to dependency changes that might break an application in the future.
