### ISSUE TITLE
Support alternative runtimes

### ISSUE THREAD

**Issue by liamwh** [serverlesstechnology/postgres-es#7]
Hi ServerlessTechnology,

First off I want to say that I love the framework so far! I am really getting into it, but noticed that I cannot compile using any runtime besides `runtime-tokio-rustls`. I'm currently using `runtime-tokio-native-tls`, and think it would be great if feature flags could be used on this crate and then passed on to the sqlx crate. Is this something you're open to addressing perhaps?

```
error: only one of ['runtime-actix-native-tls', 'runtime-async-std-native-tls', 'runtime-tokio-native-tls', 'runtime-actix-rustls', 'runtime-async-std-rustls', 'runtime-tokio-rustls'] can be enabled
  --> /Users/myaccount/.cargo/registry/src/github.com-1ecc6299db9ec823/sqlx-rt-0.6.2/src/lib.rs:23:1
   |
23 | / compile_error!(
24 | |     "only one of ['runtime-actix-native-tls', 'runtime-async-std-native-tls', \
25 | |      'runtime-tokio-native-tls', 'runtime-actix-rustls', 'runtime-async-std-rustls', \
26 | |      'runtime-tokio-rustls'] can be enabled"
27 | | );
   | |_^
```

**Comment by davegarred** [comment]
Hi @liamwh, this is a great point, thank you for posting it!
