### ISSUE TITLE
Upgrade sqlx to 0.7

### ISSUE THREAD

**Issue by liamwh** [serverlesstechnology/postgres-es#8]
As the name implies. Perhaps consider adding dependabot to your crate?

**Comment by davegarred** [comment]
Thanks for adding @liamwh, this is under investigation. The [breaking changes](https://github.com/launchbadge/sqlx/blob/main/CHANGELOG.md#breaking) introduced with 0.7 may require a major versioning here.

**Comment by davegarred** [comment]
Dependency updated in `main`.

**Comment by davegarred** [comment]
Published in v0.4.10
